services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: yllbaba
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: bankdb
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U yllbaba -d bankdb" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - backend_network
  eurekaserver:
    image: "ylli-berisha/eurekaserver"
    container_name: "eurekaserver"
    ports:
      - "8070:8070"
    healthcheck:
      test: "curl --fail --silent localhost:8070/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s
    deploy:
      resources:
        limits:
          memory: 600m
    networks:
      - backend_network
  accounts:
    image: "ylli-berisha/accounts-service"
    container_name: "accounts-service"
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 600m
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/bankdb
      SPRING_DATASOURCE_USERNAME: yllbaba
      SPRING_DATASOURCE_PASSWORD: secret
      SPRING_JPA_HIBERNATE_DDL_AUTO: create-drop
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
    networks:
      - backend_network
    depends_on:
      db:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    healthcheck: # Added healthcheck
      test: "curl --fail --silent localhost:8080/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s
  audit:
    image: "ylli-berisha/audit-service"
    container_name: "audit-service"
    ports:
      - "8100:8100"
    deploy:
      resources:
        limits:
          memory: 600m
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/bankdb
      SPRING_DATASOURCE_USERNAME: yllbaba
      SPRING_DATASOURCE_PASSWORD: secret
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
    networks:
      - backend_network
    depends_on:
      db:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    healthcheck: # Added healthcheck
      test: "curl --fail --silent localhost:8100/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s
  transactions:
    image: "ylli-berisha/transactions-service"
    container_name: "transactions-service"
    ports:
      - "8110:8110"
    deploy:
      resources:
        limits:
          memory: 600m
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/bankdb
      SPRING_DATASOURCE_USERNAME: yllbaba
      SPRING_DATASOURCE_PASSWORD: secret
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
    networks:
      - backend_network
    depends_on:
      db:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    healthcheck: # Added healthcheck
      test: "curl --fail --silent localhost:8110/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s
  users:
    image: "ylli-berisha/users-service"
    container_name: "users-service"
    ports:
      - "8120:8120"
    deploy:
      resources:
        limits:
          memory: 600m
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/bankdb
      SPRING_DATASOURCE_USERNAME: yllbaba
      SPRING_DATASOURCE_PASSWORD: secret
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
    networks:
      - backend_network
    depends_on:
      db:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    healthcheck: # Added healthcheck
      test: "curl --fail --silent localhost:8120/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

  gatewayserver:
    image: ylli-berisha/gatewayserver
    container_name: "gatewayserver"
    ports:
      - "8072:8072"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
    networks:
      - backend_network
    depends_on:
      db:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
      accounts:
        condition: service_healthy
      audit:
        condition: service_healthy
      transactions:
        condition: service_healthy
      users:
        condition: service_healthy

networks:
  backend_network:
    driver: bridge