services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: yllbaba
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d