server:
  port: 8072

jwt:
  secret: zMkyTsdyWe275ZP5VIpFKKRV8zO9fQFXqP45A129EM8=

spring:
  application:
    name: "gatewayserver"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
  main:
    web-application-type: reactive

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
  info:
    env:
      enabled: true

eureka:
  instance:
    preferIpAddress: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8070/eureka/

info:
  app:
    name: "gatewayserver"
    description: "Edge server for the application"
    version: "1.0.0"

logging:
  level:
    org.springframework.security: TRACE
    org.springframework.web: TRACE
    reactor.netty: TRACE


resilience4j.circuitbreaker:
  configs:
    default:
        sliding-window-size: 10
        permitted-number-of-calls-in-half-open-state: 2
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10000