spring:
  application:
    name: users-service
  datasource:
    url: jdbc:postgresql://localhost:5432/usersdb
    username: "ylli-users"
    password: "secret"
    driver-class-name: org.postgresql.Driver
