server:
  port: 8120

spring:
  application:
    name: users-service
  datasource:
    url: jdbc:postgresql://localhost:5433/bankdb
    username: "yllbaba"
    password: "secret"
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update