package com.ylli.shared.enums;

public enum AuditType {
    LOGIN,
    LOGOUT,
    FAILED_LOGIN,
    MONEY_TRANSFERRED,
    MONEY_WITHDRAWN,
    LOAN_APPROVED,
    LOAN_DECLINED,
    LOAN_REPAID,
    LOAN_APPLIED,
    TRANSACTION_APPROVED,
    TRANSACTION_DECLINED,
    USER_CREATED,
    USER_UPDATED,
    PASSWORD_CHANGED,
    ACCOUNT_LOCKED,
    ACCOUNT_UNLOCKED,
    EMAIL_CHANGED,
    PHONE_CHANGED
}
