package com.ylli.shared.enums;

public enum AuditType {
    FAILED_LOGIN,
    MONEY_TRANSFERRED,
    LOAN_APPROVED,
    LOAN_DECLINED,
    LOAN_CHANGES_PROPOSED,
    LOAN_REPAID,
    LOAN_APPLIED,
    DEPOSIT_MADE,
    ACCOUNT_APPLICATION_SUBMITTED,
    ACCOUNT_APPLICATION_APPROVED,
    ACCOUNT_APPLICATION_REJECTED,
    PASSWORD_CHANGED,
    ACCOUNT_LOCKED,
    ACCOUNT_UNLOCKED,
    TRANSACTION_REVERTED,
    NOT_ENOUGH_FUNDS,
    LOAN_REJECTED,
    LOAN_CHANGES_ACCEPTED,
    LOAN_CHANGES_REJECTED,
    WITHDRAWAL_MADE,
    USER_SIGNED_UP,
    USER_LOGGED_IN
}
