spring:
  application:
    name: audit-service
  datasource:
    url: jdbc:postgresql://localhost:5432/auditdb
    username: "ylli-audit"
    password: "secret"
    driver-class-name: org.postgresql.Driver
